name: Deploy to AKS

on:
  push:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx build -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp --push .
      env:
        DOCKER_BUILDKIT: 1

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Set up Azure CLI
      uses: azure/cli@v1
      with:
        azcliversion: 2.0.72

    - name: Log in to Azure
      run: az login --service-principal --username ${{ secrets.AZURE_SERVICE_PRINCIPAL_ID }} --password ${{ secrets.AZURE_SERVICE_PRINCIPAL_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Deploy to AKS
      run: |
        az aks get-credentials --resource-group "rgpythonapp" --name "myapp"
        kubectl apply -f k8s/deployment.yaml  # Adjust the path to your Kubernetes deployment file